### ISSUE TITLE
KAMPI renamed GROOK

### ISSUE THREAD

**Issue by zkgell** [vatpac-technology/sops#309]
KAMPI has been renamed GROOK in 2409.
KAMPI6 replaced with GROOK6

**Comment by Augzer** [comment]
Additional changes at other Aerodromes.

Brisbane ISPON ONE -> ISPON 2

Canberra AD elevation changed on charts that depict it.

Perth

- Depicts Runway Transitions on the IPMOR star
- SOLUS3 Star (validity NR)
- Waypoint KAVLI replaces BEVLY (previous cycle)
- Waypoint LAVEX replaces GRENE (previous cycle)
- BEVLY AND GRENE Stars renamed to KAVLI AND LAVEX (previous cycle)

**Comment by mattkelly4** [comment]
Is any further action required on this? KAMPI -> GROOK changes have been made already and we don't publish procedure numbers (e.g. SOLUS**3**) in the SOPs.

**Comment by Augzer** [comment]
I don't think so but Alex expressed he wants to check the Master list of changes for the AIS when it releases before he closes the issue. To make sure. Because I just read through the DAPs for charts that had the 5/09 date. Small chance there's other items that changed like in the FACs or something.
