### ISSUE TITLE
Non Jet can take Procedural SID - YBBN

### ISSUE THREAD

**Issue by bhendrie** [vatpac-technology/sops#356]
SOP state non-jets cant take a sid. Looking at a recent real world example QLK2362 on Flightaware, they are shown flying the SANEG SID.

**Comment by alphadelta332** [comment]
> SOP state non-jets cant take a sid. Looking at a recent real world example QLK2362 on Flightaware, they are shown flying the SANEG SID.

Thanks for bringing this up. Without knowing exactly what was going on IRL, the Non-Jet aircraft was likely assigned the Procedural SID as the controllers were able to mitigate the risk of a faster following Jet on the same SID, on a purely ad-hoc basis.

That is harder to mitigate on VATSIM, since controllers may not be necessarily looking for these potential conflicts, so the Radar SID is safer to assign as a blanket rule
